### ISSUE TITLE
1-shot learning accuracy.

### ISSUE THREAD

**Issue by aiwithshekhar** [MegaYEye/VPEReducedHubness#1]
Can you please tell me which values are corresponding to the table in your paper? These results are for GTSRB--->GTSRB

Below results are from best_iou_triggeredByVal.txt
Best score epoch:  94
acc cls: 0.8648  acc all: 0.9020  rank mean: 292.0216 
acc tr cls: 0.9299  acc te cls: 0.7967 (does the table 86.51 refer to this.)
top3: 0.9699  top5: 0.9879

**Comment by MegaYEye** [comment]
It has been a long time since I worked on this project. Please let me know if I am wrong. 

Our work is an incremental work from VPE (https://arxiv.org/pdf/1904.08482.pdf). GTSRB setting can be found In VPE paper, page 6 line 1: "evaluate the performance on the test set of all 43 classes.". The class-wise accuracy and the sample-wise accuracy corresponds to acc cls: 0.8648 acc all: 0.9020 .

**Comment by aiwithshekhar** [comment]
Thanks for replying and yeah whatever you said was correct.
My question was out of these four scores `acc cls, acc all, acc tr cls, acc te cls` which one of these have you reported in you paper which is 86.51.

Also this code base is not reproducible, i ran it two times and got different output, below is the sample. So how you made sure that improvement in the score is because of new modification of top of VPE or because of the randomness due to reproducibility.

![CODE_RERUN](https://user-images.githubusercontent.com/31220538/126863805-4afd9222-24c3-41ad-9c2b-6c2e565a185f.JPG)

**Comment by MegaYEye** [comment]
Sorry but I forget the accuracy correspondence - The answer can be obtained by reproducing the VPE code. We found the correspondence by reproducing the results from VPE paper first.

The reported performance is a statistical value from multiple experiments (within a confidence interval). The improvement is confirmed by plotting the confidence interval of both algorithms from multiple runs. The randomness is not equivalent to  ``not reproducible''. 

Hope that helps.

**Comment by aiwithshekhar** [comment]
Thanks it sounds very clear to me, one last question.

As presently for every sign we have a single prototype. I wanted to ask if we have multiple prototypes belonging to same sign, do you have any thoughts on that?
I have attached a sample image of what i meant.
![tem](https://user-images.githubusercontent.com/31220538/126938422-f10c9445-3073-4b9f-8693-77747861be29.JPG)

**Comment by MegaYEye** [comment]
The most concise way I can come up with is to treat them as two separate categories during training, but do 2-shot learning during testing. In other words, to count as "no parking" category if either of the templates hits.

But this is an engineering solution. If you are working on theoretical improvements, it may make the solution more interesting.

**Comment by aiwithshekhar** [comment]
yeah i was kind of working on that, thanks so much for all your answers, really appreciate it!!
